[tool.poetry]
name = "venn"
version = "0.2.0"
description = "Work in multiple virtual environments simultaneously with ease."
authors = ["Payson Wallach <paysonwallach@icloud.com>"]
license = "ISC"
readme = "README.md"
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.4"
cleo = "^0.7.5"
env = { git = "https://github.com/paysonwallach/env.git", tag = "0.1.2" }
virtualenvwrapper = "^4.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
venn = "venn.cli:main"
